# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0003_auto_20170627_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discography',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
