# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_auto_20170627_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandprofile',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='Instagram handle'),
        ),
    ]
