# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0006_bandprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandprofile',
            name='googleplus_handle',
            field=models.CharField(blank=True, max_length=320, null=True, verbose_name='Google plus'),
        ),
    ]
