# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0007_bandprofile_googleplus_handle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('sub_title', models.CharField(max_length=120)),
                ('share_message', models.TextField(default='Mi Casa live in Edmonton, a different flavour from what you are used to, be there or miss out!!')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
